### ISSUE TITLE
[macOS] Local prompting doesn't work

### ISSUE THREAD

**Issue by HenryDev** [MaidFoundation/maid#163]
After successfully loading a local GGUF model, the app cannot respond to prompts. Exception at line:
https://github.com/MaidFoundation/maid/blob/49c4b6cf55f5cfde62d45499b6ee275b1fd16f57/lib/core/bindings.dart#L31C16-L31C17
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'core_init': dlsym(RTLD_DEFAULT, core_init): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      NativeLibrary._core_initPtr (package:maid/core/bindings.dart:31:78)
#2      NativeLibrary._core_initPtr (package:maid/core/bindings.dart)
#3      NativeLibrary._core_init (package:maid/core/bindings.dart:34:7)
#4      NativeLibrary._core_init (package:maid/core/bindings.dart)
#5      NativeLibrary.core_init (package:maid/core/bindings.dart:25:12)
#6      LocalGeneration._init (package:maid/core/local_generation.dart:113:20)
#7      LocalGeneration.prompt (package:maid/core/local_generation.dart:137:7)

![image](https://github.com/MaidFoundation/maid/assets/1912465/7e99dae9-5eb2-4aad-9f66-a622dcaa4cfd)

**Comment by danemadsen** [comment]
does it cause a crash to desktop / segfault? It looks like its not finding the library

**Comment by HenryDev** [comment]
No. It just hangs like the screenshot with the 3 dots. 
I was looking into how FFI works and found [this Using FFI in a Flutter plugin codelab](https://codelabs.developers.google.com/codelabs/flutter-ffigen#4), where it has 
```
  if (Platform.isMacOS || Platform.isIOS) {
    return DynamicLibrary.open('$_libName.framework/$_libName');
  }
```
but in lib/core/local_generation.dart:46 the `_loadNativeLibrary()` does `DynamicLibrary.process()`, seems could be it.

**Comment by danemadsen** [comment]
yeah DynamicLibrary.process() is most likely wrong. Its a hangover from sherpa before I took over development. If you know the proper way of doing it give it a try

**Comment by danemadsen** [comment]
For anyone who wants to try tackle this here's some good resources:

https://github.com/moslite/flutter_ffigen_app/blob/main/macos
https://github.com/moslite/flutter_ffigen_app/blob/main/ios

**Comment by Foul-Tarnished** [comment]
use faraday or LLMStudio, they are made for desktops PC, and the, support Apple Silicon
